# -*- coding: utf-8 -*-
"""
Created on Sat Apr  1 14:19:05 2017

@author: Aayushi
"""

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
#import regex
import re
import csv as csv
import nltk
import openpyxl

#start process_tweet
def processTweet(tweet):
    # process the tweets

    #Convert to lower case
    tweet = tweet.lower()
    #Convert www.* or https?://* to URL
    tweet = re.sub('((www\.[^\s]+)|(https?://[^\s]+))','URL',tweet)
    #Convert @username to AT_USER
    tweet = re.sub('@[^\s]+','AT_USER',tweet)
    #Remove additional white spaces
    tweet = re.sub('[\s]+', ' ', tweet)
    #Replace #word with word
    tweet = re.sub(r'#([^\s]+)', r'\1', tweet)
    #trim
    tweet = tweet.strip('\'"')
    return tweet
#end

#Read the tweets one by one and process it
#fp = open('neutral_tweets.txt', 'r')
#line = fp.readline()

#while line:
#    processedTweet = processTweet(line)
#    print (processedTweet)
#    line = fp.readline()
#end loop
#fp.close()
stopWords = []

#start replaceTwoOrMore
def replaceTwoOrMore(s):
    #look for 2 or more repetitions of character and replace with the character itself
    pattern = re.compile(r"(.)\1{1,}", re.DOTALL)
    return pattern.sub(r"\1\1", s)
#end

#start getStopWordList
def getStopWordList(stopWordListFileName):
    #read the stopwords file and build a list
    stopWords = []
    stopWords.append('AT_USER')
    stopWords.append('URL')

    fp = open(stopWordListFileName, 'r')
    line = fp.readline()
    while line:
        word = line.strip()
        stopWords.append(word)
        line = fp.readline()
    fp.close()
    return stopWords
#end

#start getfeatureVector
def getFeatureVector(tweet):
    featureVector = []
    #split tweet into words
    words = tweet.split()
    for w in words:
        #replace two or more with two occurrences
        w = replaceTwoOrMore(w)
        #strip punctuation
        w = w.strip('\'"?,.')
        #check if the word stats with an alphabet
        val = re.search(r"^[a-zA-Z][a-zA-Z0-9]*$", w)
        #ignore if it is a stop word
        if(w in stopWords or val is None):
            continue
        else:
            featureVector.append(w.lower())
    return featureVector
#end

#Read the tweets one by one and process it
fp = open('positive_tweets.txt', 'r')
line = fp.readline()

st = open('stopwords.txt', 'r')
stopWords = getStopWordList('stopwords.txt')

while line:
    processedTweet = processTweet(line)
    featureVector = getFeatureVector(processedTweet)
    print (featureVector)
    line = fp.readline()
#end loop
fp.close()
inpTweets1 = csv.reader(open('preprocessed_positive_tweets.csv', 'r'), delimiter=',', quotechar='|')
 

tweets = []
for row in inpTweets1:
   # sentiment = row[0]
    tweet = row[0]
    processedTweet = processTweet(tweet)
    featureVector = getFeatureVector(processedTweet)
    tweets.append((featureVector, "positive"));
 
inpTweets2 = csv.reader(open('preprocessed_neutral_tweets.csv', 'r'), delimiter=',', quotechar='|')


for row in inpTweets2:
   # sentiment = row[0]
    tweet = row[0]
    processedTweet = processTweet(tweet)
    featureVector = getFeatureVector(processedTweet)
    tweets.append((featureVector, "neutral"));
                
inpTweets3 = csv.reader(open('preprocessed_negative_tweets.csv', 'r'), delimiter=',', quotechar='|')

for row in inpTweets3:
   # sentiment = row[0]
    tweet = row[0]
    processedTweet = processTweet(tweet)
    featureVector = getFeatureVector(processedTweet)
    tweets.append((featureVector, "negative"));

#endloop
#start extract_features
featureList = ['india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali','festive', 'cooking', 'relished', 'laddos',
 'goldenexperience','hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete', 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience', 'card', 'getluckywithmyntra','anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly','plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india','nich', 'yaar','totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye','hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra','bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape','friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'canvas5', 'mah', 'battery', 'cameras', 'ram', 'inch', 'fhd', 'display', 'runs', 'android', 'lollipop', 'micromaxcanvas5',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 
 'card', 'getluckywithmyntra',
 'bjp', 'feels', 'offended', 'word', 'intolerance', 'aimed', 'chor', 'ki', 'daadhi',
 'khan', 'ko', 'salam', 'karnewal', 'kejriwal', 'batai', 'kaha', 'hai', 'liar',
 
 'card', 'getluckywithmyntra',
 'uber', 'driver', 'life', 'jail', 'till', 'death', 'rape',
 
 'friend',
 'free', 'rapidly', 'confidentially',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'madhuji', 'execute', 'power', 'attorney', 'fvg', 'execute', 'affidavi', 'international', 'court', 'etc',
 'festive', 'season', 'air', 'india', 'schemes', 'web',
 'millions', 'precise', 'millions', 'born', 'months',
 'seenthechange', 'heard', 'radio', 'morning', 'welcome', 'minister', 'shell', 'life', 'ambulance',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'music', 'soul', 'heard', 'universe',
 'todays', 'failures', 'success',
 'helen', 'keller', 'story', 'life',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'plane', 'crashes', 'shortly', 'taking', 'airport', 'south', 'sudan', 'killing', 'people', 'board', 'reuters',
 'complete',
 
 'diwali', 'shopping', 'gifts', 'family', 'loads', 'sweets', 'crackers',
 'goldenexperience',
 
 'card', 'getluckywithmyntra',
 'anand', 'sharma', 'read', 'original', 'preamble', 'changed', 'duo', 'garner', 'votes', 'faced', 'defeat',
 'dieing', 'win', 'meriwatchshaktimaan', 'contest', 'wish', 'won', 'eagerly',
 'plz', 'reply', 'whn', 'announce', 'winner',
 'kailashvijayvargiyaleaveindia', 'plz', 'fuck', 'country', 'legend', 'brought', 'laurels', 'india',
 'nich', 'yaar',
 'totally', 'agree',
 'ye', 'hona', 'hi', 'chahiye',
 'hehehehehe',
 'else', 'mainstream',
 'abuse', 'cause', 'created', 'guts', 'reaction', 'modiji', 'mms',
 'hi', 'rajesh', 'touch', 'regarding',
 'nestle', 'newly', 'manufactured', 'maggi', 'found', 'safe', 'start', 'retail', 'sales', 'month', 'pti',
 'areh', 'mujhe', 'bhi', 'jana', 'tha',
 'india', 'democratic', 'country', 'support', 'wish', 'kingkhan', 'dont', 'support', 'king',
 'participate', 'subahbologoodknight', 'spot', 'win', 'contest', 'win', 'amazing', 'knight',
 'hw', 'ppc', 'transfrm', 'agriculture', 'sustainable', 'engine', 'harsimrat', 'kaur', 'badal', 'devendra', 'gangadharrao', 'fadnavis', 'wef',
 'mean', 'twitter',
 'investigate', 'comprehensively', 'heinous', 'crimes', 'yrs', 'detect', 'mitigating', 'circumstances', 'crime', 'none', 'treat', 'adults',
 'changeisbeautiful', 'ans', 'children', 'succeed', 'book', 'helped', 'lot', 'parenting',
 'barack', 'obama', 'ne', 'bola', 'tha', 'hum', 'indians', 'ko', 'srk', 'ki', 'respect', 'krni', 'chahiye', 'aur', 'bjp', 'waale', 'saale', 'paagal', 'log', 'kailashvijayvargiyaleaveindia',
 'getluckywithmyntra',
 'wish', 'winning', 'card', 'lead', 'win', 'time',
 'carry', 'love', 'hard', 'thank', 'lechalokhushiyan',
 'girls', 'named', 'dewi', 'assistant', 'named', 'setyowati', 'dewi', 'devout', 'muslim', 'salaam', 'folded', 'hands',
 'send', 'wishes', 'police', 'personnel', 'late', 'hours', 'lechalokhushiyan',
 'adity', 'nath', 'fails', 'understand', 'muslims', 'shahrukh', 'living', 'india', 'hafij', 'saeed', 'happen', 'unimaginable',
 'nautankinews', 'muslim', 'mean', 'am',
 'fittest', 'survival', 'aspects', 'happy', 'diwali',
 
 'festive', 'cooking', 'relished', 'laddos',
 'goldenexperience',
 'hashtag', 'thingstoleakinsteadofthealbum', 'top20', 'trends', 'tuesday', 'trndnl',
 'food', 'parks', 'coming', 'country', 'help', 'farmers', 'wil', 'utilize', 'produce', 'cultivated', 'farmers',
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned',
 'posted', 'photo', 'lotus', 'temple',
 'cease', 'amaze', 'please', 'policy', 'am', 'getting', 'spoilt', 'care',
 'disunity', 'world', 'note', 'glories', 'thishindu', 'minorities', 'dictate', 'terms', 'unite',
 'brave', 'heart', 'speak', 'truth',
 'action', 'words',
 'course', 'killing', 'people', 'name', 'disagree', 'inkattacks', 'sweet', 'nothings',
 'healthy', 'reasons', 'eat', 'capsicum',
 'risingcare', 'seniorcare', 'healthytips', 'kolkata',
 'supposed', 'silent', 'playing', 'blast', 'terminal',
 'birthdays', 'deserve', 'special', 'dm', 'details', 'special',
 'congrats', 'proud',
 'mwin', 'india', 'pakistan', 'draw', 'lessons', 'policy', 'national', 'health',
 'mwin', 'air', 'pollution', 'causing', 'health', 'disaster', 'india', 'professor', 'neelam', 'kler', 'told', 'india',
 'stigmabase', 'india', 'fight', 'global', 'warming', 'india', 'key', 'player',
 'thanks', 'am', 'glad', 'send', 'wishes', 'brothers', 'border', 'lechalokhushiyan',
 'stigmabase', 'india', 'draws', 'praise', 'plan', 'foreign', 'surrogacy', 'surrogacy', 'capital',
 'forget', 'tweet', 'subahbologoodknight', 'share', 'picture', 'message', 'loved', 'spread', 'word',
 'inhrdn15', 'pillar', 'success', 'brazilian', 'carnival', 'samba', 'schools', 'mumbai', 'dabbawalas',
 'discussion', 'wef', 'india', 'skills', 'initiative', 'drive', 'business', 'bottom', 'line', 'support', 'gainful', 'employment', 'wef',
 'doing', 'nice', 'sending', 'wishes', 'people', 'celebrate', 'diwali', 'lechalokhushiyan',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'pak', 'wil', 'undrstnd', 'tht', 'agressor', 'suffrd', 'tamely', 'yrs', 'shown', 'position',
 'indian', 'entry', 'international', 'competition', 'section', 'iffi2015', 'cinemawala', 'directed', 'kaushik', 'ganguly',
 'receive', 'wonderful', 'surprise', 'gift', 'cherish', 'forever',
 
 'surprise', 'gift',
 'lingard', 'star',
 'recorded', 'karnataka', 'southindia', 'travelling', 'bangalore', 'mumbai',
 'indianraiway', 'train', 'goon', 'travel',
 'diwali', 'celebration', 'begins', 'happiness', 'lechalokhushiyan',
 'morning', 'sweet', 'hrt',
 'diwali', 'celebration', 'coming', 'lifeatkr',
 'glad', 'connect', 'humbre', 'nice', 'day',
 'campaign', 'bihar', 'final', 'phase', 'alliance', 'claiming', 'nov', 'celebrates', 'deliberates',
 'animal', 'lovers', 'bharat', 'world', 'helpful2', 'respect', 'sentiments', 'democracy',
 'thank', 'communist', 'cabal', 'vitiated', 'atmosphere', 'day', 'independence',
 'chinese', 'central', 'bank', 'invests', 'indian', 'govt', 'bonds', 'economic', 'times', 'mobile',
 'maligned', 'anti', 'national', 'liberal', 'means', 'deal', 'sanjay', 'rajoura', 'nails',
 'vip', 'culture', 'person', 'shell', 'life', 'vip', 'movement',
 'selfi', 'office',
 'candyclick', 'genpact', 'silokhera', 'dlf', 'sez',
 'flowchart', 'manufactured', 'artificial', 'intolerance', 'awardwapsi', 'controversy',
 
 'image', 'nationalist', 'view',
 'road', 'speed',
 
 'traveling', 'travel', 'travelgram', 'travelingram',
 'food', 'processing', 'brings', 'partnership', 'agriculture', 'hour', 'due', 'rural', 'distress',
 'natural', 'paragliding', 'base', 'world', 'billing',
 'screaming', 'loud', 'hearing', 'launch', 'bluefilmfestival',
 
 'cant', 'wait', 'question', 'bluefilmfestival',
 
 'card',
 'getluckywithmyntra',
 
 'lighting', 'diyas', 'watch', 'golden', 'glow', 'light', 'spread', 'memorable', 'experience',
 'goldenexperience',
 'reason', 'return', 'awards', 'am', 'proud', 'accomplished', 'intolerance', 'form', 'intolerancerising',
 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'getluckywithmyntra', 'card',
 'cutiiee', 'lovely', 'sister', 'muuaahh', 'sikandra', 'rao',
 'developing', 'brand', 'serve', 'quality', 'services', 'people',
 'webenfolds',
 'type', 'help', 'tell', 'na',
 'huge', 'shout',
 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife', 'livinghandsomelife',
 'wlcom',
 'respect', 'nation', 'earned', 'selfless', 'service', 'returned']
def extract_features(tweet):
    tweet_words = set(tweet)
    features = {}
    for word in featureList:
        features['contains(%s)' % word] = (word in tweet_words)
    return features
#end

# Get tweet words
#end loop

# Remove featureList duplicates
featureList = list(set(featureList))

# Extract feature vector for all tweets in one shote
training_set = nltk.classify.util.apply_features(extract_features, tweets)

NBClassifier = nltk.NaiveBayesClassifier.train(training_set)
workbook=openpyxl.Workbook()
AnalysedExcelSheet=workbook.active
PathAnalysedData=".\grp3_output.xlsx"
# Test the classifier

Path=".\\test_data2.xlsx"
cleanWb=openpyxl.load_workbook(Path)
cleanSheet=cleanWb.active
for row in range(1,cleanSheet.max_row+1):
   # processedTweet = processTweet(line)
    processedTestTweet = processTweet(cleanSheet['A'+str(row)].value)
    print processedTestTweet
    result=NBClassifier.classify(extract_features(getFeatureVector(processedTestTweet)))
    AnalysedExcelSheet['A'+str(row)]=processedTestTweet
    AnalysedExcelSheet['B'+str(row)]=result
    print result

workbook.save(PathAnalysedData)
